"""phase2 pgvector embeddings and nullable candidate_id

Revision ID: 0002_phase2_pgvector
Revises: 0001_initial
Create Date: 2026-07-05

Assumes Phase 1 migration id '0001_initial'. If your autogenerated Phase 1
revision id differs, update ``down_revision`` accordingly.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

from backend.core.config import settings

revision: str = "0002_phase2_pgvector"
down_revision: str | None = "0001_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Dimension follows the active embedding provider (config-driven), so the
# column matches whatever get_embedder() produces. Default provider is
# sentence-transformers/bge-small (384); Ollama/nomic is 768.
_DIM = settings.EMBEDDING_DIMENSION


def upgrade() -> None:
    """Enable pgvector, relax candidate_id, and add embedding columns."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.alter_column(
        "resumes",
        "candidate_id",
        existing_type=sa.Uuid(),
        nullable=True,
    )

    op.add_column("resumes", sa.Column("embedding", Vector(_DIM), nullable=True))
    op.add_column("jobs", sa.Column("embedding", Vector(_DIM), nullable=True))

    # IVFFlat index for cosine distance on resume embeddings.
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_resumes_embedding "
        "ON resumes USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)"
    )


def downgrade() -> None:
    """Reverse the Phase 2 schema changes."""
    op.execute("DROP INDEX IF EXISTS ix_resumes_embedding")
    op.drop_column("jobs", "embedding")
    op.drop_column("resumes", "embedding")
    op.alter_column(
        "resumes",
        "candidate_id",
        existing_type=sa.Uuid(),
        nullable=False,
    )
