"use client";

import { useEffect, useState } from "react";
import { FileText, Loader2, Download } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useStreamGenerate } from "@/hooks/useStreamGenerate";
import { getReport } from "@/services/candidateService";
import { getAccessToken } from "@/lib/api";
import type { Report } from "@/types/candidate";

const REC_VARIANT: Record<string, "success" | "default" | "secondary" | "destructive"> = {
  strongly_recommend: "success",
  recommend: "default",
  neutral: "secondary",
  not_recommend: "destructive",
};

/** Generates a hiring report via SSE and offers PDF download. */
export function ReportPanel({ jobId, candidateId }: { jobId: string; candidateId: string }) {
  const path = `/api/v1/jobs/${jobId}/candidates/${candidateId}/report`;
  const stream = useStreamGenerate(path);
  const [report, setReport] = useState<Report | null>(null);

  useEffect(() => {
    getReport(jobId, candidateId).then(setReport).catch(() => setReport(null));
  }, [jobId, candidateId]);

  useEffect(() => {
    if (stream.status === "done") {
      getReport(jobId, candidateId).then(setReport).catch(() => {});
    }
  }, [stream.status, jobId, candidateId]);

  const downloadPdf = async () => {
    const res = await fetch(`/api/v1/jobs/${jobId}/candidates/${candidateId}/report/pdf`, {
      headers: { Authorization: `Bearer ${getAccessToken()}` },
    });
    if (!res.ok) return;
    const blob = await res.blob();
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `report_${candidateId}.pdf`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <Card>
      <CardHeader className="flex-row items-center justify-between">
        <CardTitle>Hiring report</CardTitle>
        <div className="flex gap-2">
          {report && (
            <Button size="sm" variant="outline" onClick={() => void downloadPdf()}>
              <Download className="h-4 w-4" /> PDF
            </Button>
          )}
          <Button size="sm" onClick={stream.start} disabled={stream.status === "streaming"}>
            {stream.status === "streaming" ? <Loader2 className="h-4 w-4 animate-spin" /> : <FileText className="h-4 w-4" />}
            {stream.status === "streaming" ? "Generating…" : report ? "Regenerate" : "Generate"}
          </Button>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        {stream.status === "streaming" && (
          <div className="flex items-center gap-2 rounded-md border bg-accent/40 p-3 text-sm">
            <span className="h-2 w-2 animate-pulse-dot rounded-full bg-primary" />
            Report agent synthesizing from scoring evidence…
          </div>
        )}
        {stream.error && <p className="text-sm text-destructive">{stream.error}</p>}

        {!report && stream.status === "idle" && (
          <p className="text-sm text-muted-foreground">No report yet. Generate a grounded hiring recommendation.</p>
        )}

        {report && (
          <div className="space-y-4">
            <div className="flex items-center gap-2">
              <span className="text-xs uppercase tracking-wide text-muted-foreground">Recommendation</span>
              <Badge variant={REC_VARIANT[report.recommendation ?? "neutral"]}>
                {(report.recommendation ?? "neutral").replace(/_/g, " ")}
              </Badge>
            </div>
            <p className="text-sm">{report.summary}</p>
            <div className="grid gap-4 sm:grid-cols-2">
              <Section title="Strengths" items={report.strengths} tone="success" />
              <Section title="Weaknesses" items={report.weaknesses} tone="destructive" />
            </div>
            {report.risk_factors.length > 0 && <Section title="Risk factors" items={report.risk_factors} tone="warning" />}
            {report.interview_plan && (
              <div>
                <p className="mb-1 text-xs uppercase tracking-wide text-muted-foreground">Interview plan</p>
                <p className="text-sm text-muted-foreground">{report.interview_plan}</p>
              </div>
            )}
            {report.model_used && (
              <p className="text-right text-xs text-muted-foreground">Generated by {report.model_used}</p>
            )}
          </div>
        )}
      </CardContent>
    </Card>
  );
}

function Section({ title, items, tone }: { title: string; items: string[]; tone: "success" | "destructive" | "warning" }) {
  const dot = tone === "success" ? "bg-success" : tone === "destructive" ? "bg-destructive" : "bg-warning";
  return (
    <div>
      <p className="mb-1.5 text-xs uppercase tracking-wide text-muted-foreground">{title}</p>
      <ul className="space-y-1">
        {(items.length ? items : ["None noted."]).map((item, i) => (
          <li key={i} className="flex items-start gap-2 text-sm">
            <span className={`mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full ${dot}`} />
            {item}
          </li>
        ))}
      </ul>
    </div>
  );
}
